### ISSUE TITLE
ABI has changed in 177f1df9

### ISSUE THREAD

**Issue by jengelh** [libyal/libfwevt#3]
Commit 177f1df9fec40c205fc6dbfc356fd17ed56737f2 removed a number of functions.
This consitutes an ABI break, and the release 20220723 should have bumped the SO number from libfwevt.so.1 to libfwevt.so.2.

**Comment by jengelh** [comment]
This has already caused fallout

```
# LD_BIND_NOW=1 ldd -r /usr/lib64/libwrc.so.1
        linux-vdso.so.1 (0x00007fffe1bcf000)
        libcerror.so.1 => /lib64/libcerror.so.1 (0x00007f15eda90000)
        libcdata.so.1 => /lib64/libcdata.so.1 (0x00007f15eda72000)
        libclocale.so.1 => /lib64/libclocale.so.1 (0x00007f15eda6c000)
        libcnotify.so.1 => /lib64/libcnotify.so.1 (0x00007f15eda65000)
        libuna.so.1 => /lib64/libuna.so.1 (0x00007f15ed9b6000)
        libbfio.so.1 => /lib64/libbfio.so.1 (0x00007f15ed99e000)
        libfvalue.so.1 => /lib64/libfvalue.so.1 (0x00007f15ed973000)
        libfwevt.so.1 => /lib64/libfwevt.so.1 (0x00007f15ed950000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f15ed600000)
        libcthreads.so.1 => /lib64/libcthreads.so.1 (0x00007f15ed943000)
        libcfile.so.1 => /lib64/libcfile.so.1 (0x00007f15ed939000)
        libcpath.so.1 => /lib64/libcpath.so.1 (0x00007f15ed92e000)
        libfdatetime.so.1 => /lib64/libfdatetime.so.1 (0x00007f15ed918000)
        libfguid.so.1 => /lib64/libfguid.so.1 (0x00007f15ed910000)
        libfwnt.so.1 => /lib64/libfwnt.so.1 (0x00007f15ed8f7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f15edad4000)
        libcsplit.so.1 => /lib64/libcsplit.so.1 (0x00007f15ed8ef000)
undefined symbol: libfwevt_provider_get_event   (/usr/lib64/libwrc.so.1)
```

**Comment by joachimmetz** [comment]
What version of libwrc ? This is likely an older version since WEVT_TEMPLATE support was removed recently

> This consitutes an ABI break, and the release 20220723 should have bumped the SO number from libfwevt.so.1 to libfwevt.so.2.

Nope, this library should not have been packaged without checking with the maintainers first.

Note that this is an experimental library and per https://github.com/libyal/libyal/wiki:

```
experimental; still very much work in progress, things will very likely break and change;
```

**Comment by jengelh** [comment]
This occurs when a Linux system has any existing libwrc build, e.g. the most recent release 20220104.
If libfwevet had received a bump, then libwrc would not load for reason of a missing file (since libfwevt.so.1 would be gone and replaced by libfwevt.so.2 by the system's package manager). That is preferable to seeing unresolvable symbols, since glibc ld.so implements lazy resolution, which means programs can abort in the middle of execution. Moreover, since the package manager also sees libfwevt.so.1 going away, it would avoid proposing the fwevt-20220723 update for users in the first place, since wrc still has a requirement on fwevt.so.1.

I do not think the classification into experimental/alpha makes a lot of sense; the software is out there and people are using it.

**Comment by joachimmetz** [comment]
> I do not think the classification into experimental/alpha makes a lot of sense; the software is out there and people are using it.

that's your opinion, I disagree. 

> This occurs when a Linux system has any existing libwrc build, e.g. the most recent release 20220104.

Most recent pre-release is 20220720

**Comment by jengelh** [comment]
The interface number should not be tied to the perceived status of the project, but to the releases made. (There is no specific meaning in the SO number, it's meant to be a counter.)
